package tr.ckale.bada.termOwl.model.impl;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;

import tr.ckale.bada.termOwl.model.*;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultVerticalCS <br>
 * @version generated on Wed Dec 21 09:21:50 MSK 2016 by Alperen
 */
public class DefaultVerticalCS extends WrappedIndividualImpl implements VerticalCS {

    public DefaultVerticalCS(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
