package tr.ckale.bada.termOwl.model;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: VerticalDatum <br>
 * @version generated on Wed Dec 21 09:21:50 MSK 2016 by Alperen
 */

public interface VerticalDatum extends Datum {

    /* ***************************************************
     * Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#latlong
     */
     
    /**
     * Gets all property values for the latlong property.<p>
     * 
     * @returns a collection of values for the latlong property.
     */
    Collection<? extends Object> getLatlong();

    /**
     * Checks if the class has a latlong property value.<p>
     * 
     * @return true if there is a latlong property value.
     */
    boolean hasLatlong();

    /**
     * Adds a latlong property value.<p>
     * 
     * @param newLatlong the latlong property value to be added
     */
    void addLatlong(Object newLatlong);

    /**
     * Removes a latlong property value.<p>
     * 
     * @param oldLatlong the latlong property value to be removed.
     */
    void removeLatlong(Object oldLatlong);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
