package tr.ckale.bada.termOwl.model;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Dec 21 09:21:49 MSK 2016 by Alperen
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#administrativeRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADMINISTRATIVEREGION.<p>
     * 
     */
    public static final OWLClass CLASS_ADMINISTRATIVEREGION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#administrativeRegion"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#agriculturalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AGRICULTURALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_AGRICULTURALREGION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#agriculturalRegion"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#area
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AREA.<p>
     * 
     */
    public static final OWLClass CLASS_AREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#area"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#atm
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATM.<p>
     * 
     */
    public static final OWLClass CLASS_ATM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#atm"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#axis
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AXIS.<p>
     * 
     */
    public static final OWLClass CLASS_AXIS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#axis"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#bank
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BANK.<p>
     * 
     */
    public static final OWLClass CLASS_BANK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#bank"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#bar
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BAR.<p>
     * 
     */
    public static final OWLClass CLASS_BAR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#bar"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#barracks
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BARRACKS.<p>
     * 
     */
    public static final OWLClass CLASS_BARRACKS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#barracks"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#beach
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BEACH.<p>
     * 
     */
    public static final OWLClass CLASS_BEACH = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#beach"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#boundingBox
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOUNDINGBOX.<p>
     * 
     */
    public static final OWLClass CLASS_BOUNDINGBOX = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#boundingBox"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#bridge
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BRIDGE.<p>
     * 
     */
    public static final OWLClass CLASS_BRIDGE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#bridge"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#building
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUILDING.<p>
     * 
     */
    public static final OWLClass CLASS_BUILDING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#building"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#businessCenter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUSINESSCENTER.<p>
     * 
     */
    public static final OWLClass CLASS_BUSINESSCENTER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#businessCenter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#cafeeHouse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAFEEHOUSE.<p>
     * 
     */
    public static final OWLClass CLASS_CAFEEHOUSE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#cafeeHouse"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#cartesianCS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CARTESIANCS.<p>
     * 
     */
    public static final OWLClass CLASS_CARTESIANCS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#cartesianCS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#castle
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CASTLE.<p>
     * 
     */
    public static final OWLClass CLASS_CASTLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#castle"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#church
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHURCH.<p>
     * 
     */
    public static final OWLClass CLASS_CHURCH = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#church"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coastal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COASTAL.<p>
     * 
     */
    public static final OWLClass CLASS_COASTAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coastal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coastalLandForm
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COASTALLANDFORM.<p>
     * 
     */
    public static final OWLClass CLASS_COASTALLANDFORM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coastalLandForm"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#compoundCRS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPOUNDCRS.<p>
     * 
     */
    public static final OWLClass CLASS_COMPOUNDCRS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#compoundCRS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#continent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTINENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTINENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#continent"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coordinateReferenceSystem
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COORDINATEREFERENCESYSTEM.<p>
     * 
     */
    public static final OWLClass CLASS_COORDINATEREFERENCESYSTEM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coordinateReferenceSystem"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coordinateSystem
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COORDINATESYSTEM.<p>
     * 
     */
    public static final OWLClass CLASS_COORDINATESYSTEM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#coordinateSystem"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#datum
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATUM.<p>
     * 
     */
    public static final OWLClass CLASS_DATUM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#datum"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#department
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPARTMENT.<p>
     * 
     */
    public static final OWLClass CLASS_DEPARTMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#department"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#drainageBasin
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DRAINAGEBASIN.<p>
     * 
     */
    public static final OWLClass CLASS_DRAINAGEBASIN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#drainageBasin"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#elipsoidalCS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ELIPSOIDALCS.<p>
     * 
     */
    public static final OWLClass CLASS_ELIPSOIDALCS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#elipsoidalCS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#ellipsoid
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ELLIPSOID.<p>
     * 
     */
    public static final OWLClass CLASS_ELLIPSOID = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#ellipsoid"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#factory
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FACTORY.<p>
     * 
     */
    public static final OWLClass CLASS_FACTORY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#factory"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#falez
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FALEZ.<p>
     * 
     */
    public static final OWLClass CLASS_FALEZ = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#falez"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#farm
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FARM.<p>
     * 
     */
    public static final OWLClass CLASS_FARM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#farm"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#forest
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FOREST.<p>
     * 
     */
    public static final OWLClass CLASS_FOREST = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#forest"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#formalArea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORMALAREA.<p>
     * 
     */
    public static final OWLClass CLASS_FORMALAREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#formalArea"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#formalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORMALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_FORMALREGION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#formalRegion"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#functionalArea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUNCTIONALAREA.<p>
     * 
     */
    public static final OWLClass CLASS_FUNCTIONALAREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#functionalArea"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#functionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUNCTIONALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_FUNCTIONALREGION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#functionalRegion"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#garden
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GARDEN.<p>
     * 
     */
    public static final OWLClass CLASS_GARDEN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#garden"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#geocentricCRS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GEOCENTRICCRS.<p>
     * 
     */
    public static final OWLClass CLASS_GEOCENTRICCRS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#geocentricCRS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#geodeticDatum
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GEODETICDATUM.<p>
     * 
     */
    public static final OWLClass CLASS_GEODETICDATUM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#geodeticDatum"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#governorsOffice
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GOVERNORSOFFICE.<p>
     * 
     */
    public static final OWLClass CLASS_GOVERNORSOFFICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#governorsOffice"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#graveyard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GRAVEYARD.<p>
     * 
     */
    public static final OWLClass CLASS_GRAVEYARD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#graveyard"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hill
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HILL.<p>
     * 
     */
    public static final OWLClass CLASS_HILL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hill"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#holidayVillage
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOLIDAYVILLAGE.<p>
     * 
     */
    public static final OWLClass CLASS_HOLIDAYVILLAGE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#holidayVillage"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hospital
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOSPITAL.<p>
     * 
     */
    public static final OWLClass CLASS_HOSPITAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hospital"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hotel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOTEL.<p>
     * 
     */
    public static final OWLClass CLASS_HOTEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hotel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#humanMadeStructure
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HUMANMADESTRUCTURE.<p>
     * 
     */
    public static final OWLClass CLASS_HUMANMADESTRUCTURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#humanMadeStructure"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#island
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ISLAND.<p>
     * 
     */
    public static final OWLClass CLASS_ISLAND = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#island"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#lake
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LAKE.<p>
     * 
     */
    public static final OWLClass CLASS_LAKE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#lake"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#landForm
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LANDFORM.<p>
     * 
     */
    public static final OWLClass CLASS_LANDFORM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#landForm"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#library
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LIBRARY.<p>
     * 
     */
    public static final OWLClass CLASS_LIBRARY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#library"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#mosque
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOSQUE.<p>
     * 
     */
    public static final OWLClass CLASS_MOSQUE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#mosque"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#mountain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOUNTAIN.<p>
     * 
     */
    public static final OWLClass CLASS_MOUNTAIN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#mountain"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#municipality
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MUNICIPALITY.<p>
     * 
     */
    public static final OWLClass CLASS_MUNICIPALITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#municipality"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#naturalFeature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NATURALFEATURE.<p>
     * 
     */
    public static final OWLClass CLASS_NATURALFEATURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#naturalFeature"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#ocean
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCEAN.<p>
     * 
     */
    public static final OWLClass CLASS_OCEAN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#ocean"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#physicalFeature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICALFEATURE.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICALFEATURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#physicalFeature"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#pier
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIER.<p>
     * 
     */
    public static final OWLClass CLASS_PIER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#pier"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#place
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLACE.<p>
     * 
     */
    public static final OWLClass CLASS_PLACE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#place"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#policeStation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class POLICESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_POLICESTATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#policeStation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#pool
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class POOL.<p>
     * 
     */
    public static final OWLClass CLASS_POOL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#pool"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#port
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PORT.<p>
     * 
     */
    public static final OWLClass CLASS_PORT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#port"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#postOffice
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class POSTOFFICE.<p>
     * 
     */
    public static final OWLClass CLASS_POSTOFFICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#postOffice"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#primaryCRS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRIMARYCRS.<p>
     * 
     */
    public static final OWLClass CLASS_PRIMARYCRS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#primaryCRS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#projectedCRS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECTEDCRS.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECTEDCRS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#projectedCRS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#region
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REGION.<p>
     * 
     */
    public static final OWLClass CLASS_REGION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#region"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#restaurant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESTAURANT.<p>
     * 
     */
    public static final OWLClass CLASS_RESTAURANT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#restaurant"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#road
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROAD.<p>
     * 
     */
    public static final OWLClass CLASS_ROAD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#road"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#sandArea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SANDAREA.<p>
     * 
     */
    public static final OWLClass CLASS_SANDAREA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#sandArea"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#school
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHOOL.<p>
     * 
     */
    public static final OWLClass CLASS_SCHOOL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#school"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#sea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEA.<p>
     * 
     */
    public static final OWLClass CLASS_SEA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#sea"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#square
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SQUARE.<p>
     * 
     */
    public static final OWLClass CLASS_SQUARE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#square"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#verticalCRS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERTICALCRS.<p>
     * 
     */
    public static final OWLClass CLASS_VERTICALCRS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#verticalCRS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#verticalCS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERTICALCS.<p>
     * 
     */
    public static final OWLClass CLASS_VERTICALCS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#verticalCS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#verticalDatum
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERTICALDATUM.<p>
     * 
     */
    public static final OWLClass CLASS_VERTICALDATUM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#verticalDatum"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#vineYard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VINEYARD.<p>
     * 
     */
    public static final OWLClass CLASS_VINEYARD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#vineYard"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#vineyard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VINEYARD.<p>
     * 
     */

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#wikipediaArticle
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WIKIPEDIAARTICLE.<p>
     * 
     */
    public static final OWLClass CLASS_WIKIPEDIAARTICLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#wikipediaArticle"));

    /* ***************************************************
     * Class http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#wineFactory
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WINEFACTORY.<p>
     * 
     */
    public static final OWLClass CLASS_WINEFACTORY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#wineFactory"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#crosses
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CROSSES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CROSSES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#crosses"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hasLocationData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLOCATIONDATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLOCATIONDATA = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hasLocationData"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#isPartOf"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#overlaps
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OVERLAPS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OVERLAPS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#overlaps"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#touches
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOUCHES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOUCHES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#touches"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#wikipediaArticle
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WIKIPEDIAARTICLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WIKIPEDIAARTICLE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#wikipediaArticle"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWLTOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#BeachFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BEACHFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BEACHFLAG = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#BeachFlag"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#area
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property AREA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_AREA = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#area"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hasStar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTAR = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#hasStar"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#latitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LATITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LATITUDE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#latitude"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#latlong
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LATLONG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LATLONG = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#latlong"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#longitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LONGITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LONGITUDE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#longitude"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#population
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POPULATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POPULATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#population"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#postalCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POSTALCODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POSTALCODE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/alperen/ontologies/2016/11/geolocation#postalCode"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWLTOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
